ReuseProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static 

urlpatterns = [
    path('', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views
from django.urls import reverse



urlpatterns = [
    path('', views.home, name="home"),
    path('login/', views.loginView, name='login'),
    path('logout/', LogoutView.as_view(template_name="logout.html"), name='logout'),
    path('register/', views.register, name='register'),

     path('sobre_mi/', views.sobre_mi, name='sobre_mi'),

    path('profile/', views.profile, name='profile'),  
    path('edit_profile/', views.edit_user_profile, name='edit_profile'),
    path('home_vendedor/', views.home_vendedor, name='home_vendedor'),
    path('agregar_avatar', views.agregar_avatar, name='agregar_avatar'),

    path('agregar_ropa/', views.agregar_ropa, name='agregar_ropa'),
    path('lista-ropa/', views.lista_ropa, name='lista_ropa'),
    path('editar_ropa/<int:ropa_id>/', views.editar_ropa, name='editar_ropa'),
    path('eliminar_ropa/<int:ropa_id>/', views.eliminar_ropa, name='eliminar_ropa'),

    path('agregar_zapatos/', views.agregar_zapatos, name='agregar_zapatos'),
    path('lista-zapatos/', views.lista_zapatos, name='lista_zapatos'),
    path('editar_zapatos/<int:zapatos_id>/', views.editar_zapatos, name='editar_zapatos'),  
    path('eliminar_zapatos/<int:zapatos_id>/', views.eliminar_zapatos, name='eliminar_zapatos'),

    path('agregar_accesorios/', views.agregar_accesorios, name='agregar_accesorios'),
    path('lista-accesorios/', views.lista_accesorios, name='lista_accesorios'),
    path('editar_accesorios/<int:accesorios_id>/', views.editar_accesorios, name='editar_accesorios'),
    path('eliminar_accesorios/<int:accesorios_id>/', views.eliminar_accesorios, name='eliminar_accesorios'),

]

accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User




class Ropa(models.Model):
    nombre = models.CharField(max_length=255)
    descripcion = models.TextField()
    talla = models.CharField(max_length=10)
    marca = models.CharField(max_length=100)
    precio = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    imagen = models.ImageField(upload_to='media/ropa/')  
     # Campo para relacionar la prenda de ropa con el usuariomanage.py makemigrations
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    

class Zapatos(models.Model):
    nombre = models.CharField(max_length=255)
    descripcion = models.TextField()
    talla = models.CharField(max_length=10)
    marca = models.CharField(max_length=100)
    precio = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    imagen = models.ImageField(upload_to='media/zapatos/') 
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

class Accesorios(models.Model):
    nombre = models.CharField(max_length=255)
    descripcion = models.TextField()
    talla = models.CharField(max_length=10)
    marca = models.CharField(max_length=100)
    precio = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)  
    imagen = models.ImageField(upload_to='accesorios/')  
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=1)



class Avatar(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='avatares', blank=True, null=True)
    predeterminado = models.BooleanField(default=False)

accounts/forms.py
from django.contrib.auth.forms import UserChangeForm
from django import forms
from django.contrib.auth.models import User
from .models import  Ropa,Zapatos, Accesorios, Avatar 

class UserEditForm(UserChangeForm):

    password = forms.CharField(
        help_text="",
        widget=forms.HiddenInput(), required=False
    )

    password1 = forms.CharField(label="Contraseña", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Repetir contraseña", widget=forms.PasswordInput)

    class Meta:
        model=User
        fields = ("username", "email", "password1", "password2")

    def clean_password2(self):

        print(self.cleaned_data)

        password1 = self.cleaned_data["password1"]
        password2 = self.cleaned_data["password2"]

        if password1 != password2:
            raise forms.ValidationError("¡Las contraseñas no coinciden!")
        return password2


class RopaForm(forms.ModelForm):
    class Meta:
        model = Ropa
        fields = ['nombre', 'descripcion', 'talla', 'marca','precio', 'imagen']

class ZapatosForm(forms.ModelForm):
    class Meta:
        model = Zapatos
        fields = ['nombre', 'descripcion', 'talla', 'marca','precio', 'imagen']

class AccesoriosForm(forms.ModelForm):
    class Meta:
        model = Accesorios
        fields = ['nombre', 'descripcion', 'talla', 'marca','precio', 'imagen']



class AvatarForm(forms.ModelForm):
    class Meta:
        model = Avatar
        fields = ("imagen",)
        widgets = {
            'imagen': forms.ClearableFileInput(),  # Elimina 'attrs' para 'multiple'
        }

accounts/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm # Usa el formulario de usuario predeterminado
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden
from .forms import UserEditForm, AvatarForm, RopaForm, ZapatosForm, AccesoriosForm
from .models import Ropa, Zapatos, Accesorios, Avatar







def home(request):

    return render(request, "home.html")


def home_vendedor (request):

    return render(request, "home_vendedor.html")

def sobre_mi (request):

    return render(request, "sobre_mi.html")



@login_required
def profile(request):
    user_avatar = None
    if request.user.is_authenticated:
        try:
            user_avatar = Avatar.objects.get(user=request.user)# pylint: disable=no-member
        except Avatar.DoesNotExist:# pylint: disable=no-member
            pass

    return render(request, 'profile.html', {'user_avatar': user_avatar})



def loginView(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return render(request, "home_vendedor.html", {"mensaje": f"Bienvenidx {username}!"})
            else:
                return render(request, "home.html", {"mensaje": "Datos incorrectos"})
    else:
        form = AuthenticationForm()
    return render(request, "login.html", {"form": form})

def logoutView(request):
    logout(request)
    # No necesitas mensajes aquí
    return redirect('home')




def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, 'Registro exitoso. Ahora puedes iniciar sesión.')
            return redirect('login')
        else:
            messages.error(request, 'Error en el registro. Por favor, asegúrate de que las contraseñas coincidan.')
    else:
        form = UserCreationForm()
    return render(request, 'register.html', {'form': form})




@login_required
def edit_user_profile(request):

    usuario = request.user

    if request.method == 'POST':
        form = UserEditForm(request.POST, instance=usuario)

        if form.is_valid():

            data = form.cleaned_data
            usuario.username = data["username"]
            usuario.email = data["email"]
            usuario.set_password(data["password1"])
            usuario.save()

            return render(request, "profile.html", {"mensaje": "Datos actualizados con éxito!"})
        else:
            return render(request, "edit_profile.html", {"form": form})
    else:
        form = UserEditForm(instance=usuario)
        return render(request, "edit_profile.html", {"form": form})
    





@login_required
def agregar_ropa(request):

    if request.method == 'POST':
        form = RopaForm(request.POST, request.FILES)
        if form.is_valid():
            ropa = form.save(commit=False)
            ropa.usuario = request.user  # Asigna el usuario actual
            ropa.save()
            return redirect('lista_ropa')
    else:
        form = RopaForm()
    
    return render(request, 'agregar_ropa.html', {'form': form})

def lista_ropa(request):

    elementos_ropa = Ropa.objects.all()# pylint: disable=no-member
    return render(request, 'lista_ropa.html', {'ropa': elementos_ropa})

@login_required
def editar_ropa(request, ropa_id):

    ropa = Ropa.objects.get(pk=ropa_id)# pylint: disable=no-member

    if ropa.usuario == request.user:
        if request.method == 'POST':
            form = RopaForm(request.POST, request.FILES, instance=ropa)
            if form.is_valid():
                ropa = form.save(commit=False)
                ropa.usuario = request.user
                ropa.save()
                return redirect('lista_ropa')
            
        else:
            form = RopaForm(instance=ropa)
                # Agrega los prints de depuración aquí
        print("Formulario válido:", form.is_valid())
      
     

        return render(request, 'editar_ropa.html', {'form': form, 'ropa': ropa})
    else:
        return HttpResponseForbidden("No tienes permiso para editar esta ropa.")

@login_required
def eliminar_ropa(request, ropa_id):
    ropa = Ropa.objects.get(pk=ropa_id)# pylint: disable=no-member

    if ropa.usuario == request.user:
        ropa.delete()
        return redirect('lista_ropa')
    else:
        return HttpResponseForbidden("No tienes permiso para eliminar esta ropa.")
    
@login_required
def agregar_zapatos(request):
    if request.method == 'POST':
        form = ZapatosForm(request.POST, request.FILES)
        if form.is_valid():
            zapatos = form.save(commit=False)
            zapatos.usuario = request.user  # Establecer el usuario actual
            zapatos.save()
            return redirect('lista_zapatos')

    else:
        form = ZapatosForm()

    return render(request, 'agregar_zapatos.html', {'form': form})


def lista_zapatos(request):
    zapatos = Zapatos.objects.all()# pylint: disable=no-member
    return render(request, 'lista_zapatos.html', {'zapatos': zapatos})

@login_required
def editar_zapatos(request, zapatos_id):
    zapatos = Zapatos.objects.get(pk=zapatos_id) # pylint: disable=no-member

    if zapatos.usuario == request.user:
        if request.method == 'POST':
            form = ZapatosForm(request.POST, request.FILES, instance=zapatos)
            if form.is_valid():
                zapatos = form.save(commit=False)
                zapatos.usuario = request.user
                zapatos.save()
                return redirect('lista_zapatos')

        else:
            form = ZapatosForm(instance=zapatos)
        
        print("Formulario válido:", form.is_valid())

        return render(request, 'editar_zapatos.html', {'form': form, 'zapatos': zapatos})
    else:
        return HttpResponseForbidden("No tienes permiso para editar estos zapatos.")

@login_required
def eliminar_zapatos(request, zapatos_id):
    zapatos = Zapatos.objects.get(pk=zapatos_id)# pylint: disable=no-member  

    if zapatos.usuario == request.user:
        zapatos.delete()
        return redirect('lista_zapatos')
    else:
        return HttpResponseForbidden("No tienes permiso para eliminar estos zapatos.")
    




    
@login_required
def agregar_accesorios(request):
    if request.method == 'POST':
        form = AccesoriosForm(request.POST, request.FILES)
        if form.is_valid():
            accesorios = form.save(commit=False)
            accesorios.usuario = request.user  # Asigna el usuario actual
            accesorios.save()
            return redirect('lista_accesorios') 
    else:
        form = AccesoriosForm()
    
    return render(request, 'agregar_accesorios.html', {'form': form})


def lista_accesorios(request):
    accesorios = Accesorios.objects.all()# pylint: disable=no-member
    return render(request, 'lista_accesorios.html', {'accesorios': accesorios})

@login_required
def editar_accesorios(request, accesorios_id):
    accesorios = Accesorios.objects.get(pk=accesorios_id)# pylint: disable=no-member

    if accesorios.usuario == request.user:
        if request.method == 'POST':
            form = AccesoriosForm(request.POST, request.FILES, instance=accesorios)
            if form.is_valid():
                accesorios = form.save(commit=False)
                accesorios.usuario = request.user
                accesorios.save()
                return redirect('lista_accesorios')

        else:
            form = AccesoriosForm(instance=accesorios)

        print("Formulario válido:", form.is_valid())

        return render(request, 'editar_accesorios.html', {'form': form, 'accesorios': accesorios})
    else:
        return HttpResponseForbidden("No tienes permiso para editar estos accesorios.")

@login_required
def eliminar_accesorios(request, accesorios_id):
    accesorios = Accesorios.objects.get(pk=accesorios_id)# pylint: disable=no-member

    if accesorios.usuario == request.user:
        accesorios.delete()
        return redirect('lista_accesorios')
    else:
        return HttpResponseForbidden("No tienes permiso para eliminar estos accesorios.")
    





@login_required
def agregar_avatar(request):
    try:
        user_avatar = Avatar.objects.get(user=request.user)# pylint: disable=no-member
    except ObjectDoesNotExist:
        user_avatar = None

    if request.method == 'POST':
        form = AvatarForm(request.POST, request.FILES)
        if form.is_valid():
            data = form.cleaned_data
            if user_avatar:
                # Si el usuario ya tiene un avatar, elimina el avatar existente
                user_avatar.delete()

            avatar = Avatar(user=request.user, imagen=data["imagen"])
            avatar.save()
            return redirect('profile')

    else:
        form = AvatarForm()

    return render(request, "agregar_avatar.html", {"form": form, "user_avatar": user_avatar})

accounts/templates/agregar_accesorios.html
{% extends 'base.html' %}

{% block content %}

<section class="contenedor">
    <div class="contenedor_formulario">
        <form class="formulario" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            
            <h2>Agregar Accesorios</h2>
            
            <div class="campo">
                {{ form.nombre.label_tag }}
                {{ form.nombre }}
                {{ form.nombre.errors }}
            </div>
            
            <div class="campo">
                {{ form.descripcion.label_tag }}
                {{ form.descripcion }}
                {{ form.descripcion.errors }}
            </div>

            <div class="campo">
                {{ form.talla.label_tag }}
                {{ form.talla }}
                {{ form.talla.errors }}
            </div>
            
            <div class="campo">
                {{ form.marca.label_tag }}
                {{ form.marca }}
                {{ form.marca.errors }}
            </div>

            <div class="campo">
                {{ form.precio.label_tag }}
                {{ form.precio }}
                {{ form.precio.errors }}
            </div>
            
            <div class="campo">
                {{ form.imagen.label_tag }}
                {{ form.imagen }}
                {{ form.imagen.errors }}
            </div>
            
            <button type="submit" class="btn btn-primary">Guardar</button>
        </form>
    </div>
</section>

{% endblock %}

accounts/templates/agregar_avatar.html
<!-- 

    <div class="contenedor_formulario_profile">
        <form action="{% url 'agregar_avatar' %}" enctype="multipart/form-data" method="post">
            {% csrf_token %}
            
          
            <div class="form-group">
                {{ form.imagen.label_tag }}
                {{ form.imagen }}
                <small class="text-muted">Cargar nueva imagen de avatar</small>
            </div>

            <div class="form-check">
                {{ form.imagen.clear }}
                {{ form.imagen.clear.label_tag }}
                {{ form.imagen.clear }}
                <label class="form-check-label" for="{{ form.imagen.clear.id_for_label }}">Eliminar avatar actual</label>
            </div>

            <button type="submit" class="btn btn-primary">Guardar Cambios</button>
        </form>
    </div>

    
 -->

 <div class="contenedor_formulario_profile">
    <h2>Editar Avatar</h2>
    <form action="{% url 'agregar_avatar' %}" method="post" enctype="multipart/form-data">
        <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
        
        <!-- Campo para cargar una nueva imagen de avatar -->
        <div class="form-group">
            <label for="id_imagen">Cargar nueva imagen de avatar:</label>
            <input type="file" id="id_imagen" name="imagen">
        </div>

        <!-- Campo para eliminar el avatar -->
        <div class="form-check">
            <input type="checkbox" id="id_imagen_clear" name="imagen_clear">
            <label class="form-check-label" for="id_imagen_clear">Eliminar avatar actual</label>
        </div>

        <button type="submit" class="btn btn-primary">Guardar Cambios</button>
    </form>
</div>

accounts/templates/agregar_ropa.html
{% extends 'base.html' %}

{% block content %}

<section class="contenedor">
    <div class="contenedor_formulario">
        <form class="formulario" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            
            <h2>Agregar Ropa</h2>
            
            <div class="campo">
                {{ form.nombre.label_tag }}
                {{ form.nombre }}
                {{ form.nombre.errors }}
            </div>
            
            <div class="campo">
                {{ form.descripcion.label_tag }}
                {{ form.descripcion }}
                {{ form.descripcion.errors }}
            </div>
            
            <div class="campo">
                {{ form.talla.label_tag }}
                {{ form.talla }}
                {{ form.talla.errors }}
            </div>
            
            <div class="campo">
                {{ form.marca.label_tag }}
                {{ form.marca }}
                {{ form.marca.errors }}
            </div>

            <div class="campo">
                {{ form.precio.label_tag }}
                {{ form.precio }}
                {{ form.precio.errors }}
            </div>
                        
            <div class="campo">
                {{ form.imagen.label_tag }}
                {{ form.imagen }}
                {{ form.imagen.errors }}
            </div>
            
            <button type="submit" class="btn btn-primary">Guardar</button>
            
        </form>
    </div>
</section>

{% endblock %}

accounts/templates/agregar_zapatos.html
{% extends 'base.html' %}

{% block content %}

<section class="contenedor">
    <div class="contenedor_formulario">
        <form class="formulario" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            
            <h2>Agregar Zapatos</h2>
            
            <div class="campo">
                {{ form.nombre.label_tag }}
                {{ form.nombre }}
                {{ form.nombre.errors }}
            </div>
            
            <div class="campo">
                {{ form.descripcion.label_tag }}
                {{ form.descripcion }}
                {{ form.descripcion.errors }}
            </div>
            
            <div class="campo">
                {{ form.talla.label_tag }}
                {{ form.talla }}
                {{ form.talla.errors }}
            </div>
            
            <div class="campo">
                {{ form.marca.label_tag }}
                {{ form.marca }}
                {{ form.marca.errors }}
            </div>

            <div class="campo">
                {{ form.precio.label_tag }}
                {{ form.precio }}
                {{ form.precio.errors }}
            </div>
            
            <div class="campo">
                {{ form.imagen.label_tag }}
                {{ form.imagen }}
                {{ form.imagen.errors }}
            </div>
            
            <button type="submit" class="btn btn-primary">Guardar</button>
        </form>
    </div>
</section>

{% endblock %}

accounts/templates/base.html
<!DOCTYPE HTML>
<html>
	<head>
		{% load static %}
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'css/main.css' %}" />
		<link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link href="https://fonts.googleapis.com/css2?family=Livvic:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,900&family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
		<title>ReUse</title>
	</head>
	<body>
		<header>
		    <div class="logo">
		        <a href="/accounts/login"><img src="{% static 'imgs/logo.png' %}"  alt="Logo de la tienda"></a>
		    </div>
		    <nav>
		        <ul>
		            <li><a href="/accounts/lista-ropa" class="boton">Ropa</a></li>
		            <li><a href="/accounts/lista-zapatos" class="boton">Zapatos</a></li>
		            <li><a href="/accounts/lista-accesorios" class="boton">Accesorios</a></li>
		            <li><a href="/accounts/home_vendedor" class="boton">Agregar</a></li>
					<li><a href="/accounts/sobre_mi" class="boton">Sobre Mi</a></li>
					<li class="contenAvatar">
						{% if user.is_authenticated %}
							{% if user_avatar %}
							<a href="/accounts/profile">
								<img src="{{ user_avatar.imagen.url }}" class="avatar" alt="avatar">
							  </a>           
							{% endif %}
							<a class="btn btn-primary" href="{% url 'logout' %}">Logout</a>
						{% else %}
							<a class="btn btn-primary" href="{% url 'login' %}">Login</a>	
						{% endif %}	
		            </li>
		        </ul>
		    </nav>
		</header>


		{% block content %}


		{% endblock %}


	

		<footer>
		    <div class="copyright">
		        <p>&copy; 2023 ReUse. Todos los derechos reservados.</p>
		    </div>
		</footer>
	</body>


</html>

accounts/templates/edit_profile.html
<!-- 
      <div class="contenedor_formulario_profile">
   
        <h2>Editar Perfil de Usuario</h2>

        <form action="{% url 'edit_profile' %}" method="post">
          {% csrf_token %}
          
          <div class="form-group">
              {{ form.username.label_tag }}
              {{ form.username }}
          </div>
          
          <div class="form-group">
              {{ form.email.label_tag }}
              {{ form.email }}
          </div>

          <div class="form-group">
            {{ form.password1.label_tag }}
            {{ form.password1 }}
        </div>
    
        <div class="form-group">
            {{ form.password2.label_tag }}
            {{ form.password2 }}
        </div>
          
  
          
          <button class="btn btn-primary" type="submit">Actualizar</button>
      </form>
      
        
          <a href="{% url 'profile' %}">Cancelar</a>
      </div> -->



      <div class="contenedor_formulario_profile">
        <h2>Editar Perfil de Usuario</h2>
    
        <form action="{% url 'edit_profile' %}" method="post">
            <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
            
            <div class="form-group">
                <label for="id_username">Username:</label>
                <input type="text" id="id_username" name="username" value="{{ form.username.value }}">
            </div>
            
            <div class="form-group">
                <label for="id_email">Email:</label>
                <input type="email" id="id_email" name="email" value="{{ form.email.value }}">
            </div>
    
            <div class="form-group">
                <label for="id_password1">Password:</label>
                <input type="password" id="id_password1" name="password1">
            </div>
        
            <div class="form-group">
                <label for="id_password2">Confirm Password:</label>
                <input type="password" id="id_password2" name="password2">
            </div>
              
            <button class="btn btn-primary" type="submit">Actualizar</button>
        </form>
        
        <a href="{% url 'profile' %}">Cancelar</a>
    </div>
    

accounts/templates/editar_ropa.html
{% extends 'base.html' %}

{% block content %}
<section class="contenedor">
    <div class="contenedor_formulario">
        <form class="formulario" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <h2>Editar  Ropa</h2>
            
            <div class="campo">
                {{ form.nombre.label_tag }}
                {{ form.nombre }}
                {{ form.nombre.errors }}
            </div>
            
            <div class="campo">
                {{ form.descripcion.label_tag }}
                {{ form.descripcion }}
                {{ form.descripcion.errors }}
            </div>
            
            <div class="campo">
                {{ form.talla.label_tag }}
                {{ form.talla }}
                {{ form.talla.errors }}
            </div>
            
            <div class="campo">
                {{ form.marca.label_tag }}
                {{ form.marca }}
                {{ form.marca.errors }}
            </div>

            <div class="campo">
                {{ form.precio.label_tag }}
                {{ form.precio }}
                {{ form.precio.errors }}
            </div>
                        
            <div class="campo">
                {{ form.imagen.label_tag }}
                {{ form.imagen }}
                {{ form.imagen.errors }}
            </div>
            
            <button type="submit" class="btn btn-primary">Guardar Cambios</button>
        </form>

        <form method="post" action="{% url 'eliminar_ropa' ropa.id %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger" name="delete">Eliminar Ropa</button>
        </form>
        
        <a href="{% url 'lista_ropa' %}" class="btn btn-secondary">Cancelar cambios</a>
    </div>
</section>
{% endblock %}

accounts/templates/editar_zapatos.html
{% extends 'base.html' %}

{% block content %}
<section class="contenedor">
    <div class="contenedor_formulario">
        <form class="formulario" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <h2>Editar  Zapatos</h2>
            
            <div class="campo">
                {{ form.nombre.label_tag }}
                {{ form.nombre }}
                {{ form.nombre.errors }}
            </div>
            
            <div class="campo">
                {{ form.descripcion.label_tag }}
                {{ form.descripcion }}
                {{ form.descripcion.errors }}
            </div>
            
            <div class="campo">
                {{ form.talla.label_tag }}
                {{ form.talla }}
                {{ form.talla.errors }}
            </div>
            
            <div class="campo">
                {{ form.marca.label_tag }}
                {{ form.marca }}
                {{ form.marca.errors }}
            </div>

            <div class="campo">
                {{ form.precio.label_tag }}
                {{ form.precio }}
                {{ form.precio.errors }}
            </div>
                        
            <div class="campo">
                {{ form.imagen.label_tag }}
                {{ form.imagen }}
                {{ form.imagen.errors }}
            </div>
            
            <button type="submit" class="btn btn-primary">Guardar Cambios</button>
        </form>

        <form method="post" action="{% url 'eliminar_zapatos' zapatos.id %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger" name="delete">Eliminar</button>
        </form>
        
        <a href="{% url 'lista_zapatos' %}" class="btn btn-secondary">Cancelar cambios</a>
    </div>
</section>
{% endblock %}

accounts/templates/home.html
{% extends 'base.html' %}

{% load static %} 

{% block content %}

	<section class="contenedor">

			<h2>{{mensaje}}</h2>

			<img class="centered-image" src="{% static 'imgs/logo2.png' %}" alt="Imagen centrada">	
							
	</section>


{% endblock %}

accounts/templates/lista_ropa.html
{% extends 'base.html' %}

{% block content %}

<section class="contenedor">
    <h2>Lista de Ropa</h2>
    <div class="contenedor_listas">
        <ul class="lista">
            {% for ropa in ropa %}
                <li class="item">
                    <div class="div20 imgs">
                        <img src="{{ ropa.imagen.url }}" alt="{{ ropa.nombre }}" width="100">
                    </div>
                    <div class="div80 informacion">
                        <strong>{{ ropa.nombre }}</strong><br>
                        Descripción: {{ ropa.descripcion }}<br>
                        Talla: {{ ropa.talla }}<br>
                        Marca: {{ ropa.marca }}<br>
                        Precio: ${{ ropa.precio }}<br>
                        <div class="acciones">
                            <div class="boton-editar">
                                <form method="post" action="{% url 'editar_ropa' ropa.id %}">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-primary">Editar</button>
                                </form>
                            </div>
                            <div class="boton-eliminar">
                                <form method="post" action="{% url 'eliminar_ropa' ropa.id %}">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-danger">Eliminar</button>
                                </form>
                            </div>
                        </div>
                    </div>

                </li>
            {% endfor %}
        </ul>
    </div>
</section>
{% endblock %}

accounts/templates/logout.html
{% extends 'base.html' %}

{% block content %}

    <section class="contenedor">
        <div class="msj_despedida">

            <h1>Gracias por visitar, vuelva pronto</h1>
  
            <a href="{% url 'home'%}">Regresar al home</a>

        </div>
        <div class="msj_despedida"></div>



    </section>



{% endblock %}